const ACTION = {
    UPDATE_MESSAGE_INPUT: 'UPDATE_MESSAGE_INPUT',
    ADD_MESSAGE: 'ADD_MESSAGE',
    UPDATE_POST_INPUT: 'UPDATE_POST_INPUT',
    ADD_POST: 'ADD_POST',
    TOGGLE_MENU_TAB: 'TOGGLE_MENU_TAB',
    SET_TOKEN: 'SET_TOKEN',
}

export {ACTION}