const ACTION = {
    ADD_MESSAGE: 'ADD_MESSAGE',
    SET_MESSAGES: 'SET_MESSAGES',
    SET_DIALOGS: 'SET_DIALOGS',
    ADD_POST: 'ADD_POST',
    SET_POSTS: 'SET_POSTS',
    SET_FEED_POSTS: 'SET_FEED_POSTS',
    UPDATE_POST: 'UPDATE_POST',
    DELETE_POST: 'DELETE_POST',
    TOGGLE_MENU_TAB: 'TOGGLE_MENU_TAB',
    SET_TOKEN: 'SET_TOKEN',
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
}

export {ACTION}