export const ACTION = {
    MESSAGE: {
        ADD_MESSAGE: 'ADD_MESSAGE',
        UPDATE_MESSAGE: 'UPDATE_MESSAGE',
        SET_MESSAGES: 'SET_MESSAGES',
        UPDATE_DIALOG: 'UPDATE_DIALOG',
        ADD_DIALOG: 'ADD_DIALOG',
    },
    FEED: {
        SET_INITIAL_LOADING: 'SET_INITIAL_LOADING',
        ADD_POST: 'ADD_POST',
        SET_POSTS: 'SET_POSTS',
        UPDATE_POST: 'UPDATE_POST',
        DELETE_POST: 'DELETE_POST',
        SET_POPULAR_TAGS: 'SET_POPULAR_TAGS',
        SET_ACTUAL_TOPICS: 'SET_ACTUAL_TOPICS',
    },
    AUTH: {
        LOGIN_USER: 'LOGIN_USER',
        LOGOUT_USER: 'LOGOUT_USER',
        SET_CURRENT_USER: 'SET_CURRENT_USER',
    },
    PROFILE: {
        SET_INITIAL_LOADING: 'SET_INITIAL_LOADING',
        SET_USER: 'SET_USER',
        ADD_POST: 'ADD_POST',
        SET_POSTS: 'SET_POSTS',
        UPDATE_POST: 'UPDATE_POST',
        DELETE_POST: 'DELETE_POST',
    },
    APP: {
        TOGGLE_MENU_TAB: 'TOGGLE_MENU_TAB',
        INITIALIZE: 'INITIALIZE',
        ADD_NOTIFICATION: 'ADD_NOTIFICATION',
        REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
    },
    IMAGE: {
        ADD_IMAGE: 'ADD_IMAGE',
    }
}